language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep automake autoconf
script: autoreconf -ivf && ./configure && make -j24 && make -j24 check && sudo make install
after_failure:
 - cat test-suite.log
 - cat configure.log
